
spring:
  flyway:
   enabled: true
   locations: classpath:db/migration/non-local
   driver-class-name: org.postgresql.Driver
   baseline-on-migrate: true

  datasource:
   url: jdbc:postgresql://localhost:5432/invent_bank_db
   username: postgres
   password: postgres
